import agent from "@convex-dev/agent/convex.config";
import aggregate from "@convex-dev/aggregate/convex.config";
import betterAuth from "@convex-dev/better-auth/convex.config";
import geospatial from "@convex-dev/geospatial/convex.config";
import migrations from "@convex-dev/migrations/convex.config";
import polar from "@convex-dev/polar/convex.config";
import r2 from "@convex-dev/r2/convex.config";
import rateLimiter from "@convex-dev/rate-limiter/convex.config";
import resend from "@convex-dev/resend/convex.config";
import twilio from "@convex-dev/twilio/convex.config";
import inviteLinks from "convex-invite-links/convex.config";
import { defineApp } from "convex/server";

const app = defineApp();
app.use(betterAuth);
app.use(twilio);
app.use(rateLimiter);
app.use(resend);
app.use(r2);
app.use(migrations);
app.use(polar);
app.use(agent);
app.use(geospatial);
app.use(inviteLinks);
app.use(aggregate, { name: "aggregateCompletedAppointments" });
app.use(aggregate, { name: "aggregateSmsSent" });
app.use(aggregate, { name: "aggregateEmailsSent" });
export default app;
