allowBuilds:
  core-js: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@base-ui/react@1.6.0'
  - '@base-ui/utils@0.3.1'
  - '@cloudflare/vite-plugin@1.42.0'
  - miniflare@4.20260617.0
  - wrangler@4.102.0
patchedDependencies:
  '@tanstack/router-core@1.171.9': patches/@tanstack__router-core@1.171.9.patch
