/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ServicesIndexRouteImport } from "./routes/services.index"
import { Route as ReviewsIndexRouteImport } from "./routes/reviews.index"
import { Route as ProfileIndexRouteImport } from "./routes/profile.index"
import { Route as BecomeBarberIndexRouteImport } from "./routes/become-barber.index"
import { Route as BarbershopsIndexRouteImport } from "./routes/barbershops/index"
import { Route as BarbershopSettingsIndexRouteImport } from "./routes/barbershop-settings.index"
import { Route as AppointmentsIndexRouteImport } from "./routes/appointments/index"
import { Route as AnalyticsIndexRouteImport } from "./routes/analytics.index"
import { Route as BarbershopsBarbershopUuidRouteImport } from "./routes/barbershops/$barbershopUuid"
import { Route as AppointmentsCreateRouteImport } from "./routes/appointments/create"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: "/services/",
  path: "/services/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: "/reviews/",
  path: "/reviews/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeBarberIndexRoute = BecomeBarberIndexRouteImport.update({
  id: "/become-barber/",
  path: "/become-barber/",
  getParentRoute: () => rootRouteImport,
} as any)
const BarbershopsIndexRoute = BarbershopsIndexRouteImport.update({
  id: "/barbershops/",
  path: "/barbershops/",
  getParentRoute: () => rootRouteImport,
} as any)
const BarbershopSettingsIndexRoute = BarbershopSettingsIndexRouteImport.update({
  id: "/barbershop-settings/",
  path: "/barbershop-settings/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: "/appointments/",
  path: "/appointments/",
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: "/analytics/",
  path: "/analytics/",
  getParentRoute: () => rootRouteImport,
} as any)
const BarbershopsBarbershopUuidRoute =
  BarbershopsBarbershopUuidRouteImport.update({
    id: "/barbershops/$barbershopUuid",
    path: "/barbershops/$barbershopUuid",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppointmentsCreateRoute = AppointmentsCreateRouteImport.update({
  id: "/appointments/create",
  path: "/appointments/create",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/appointments/create": typeof AppointmentsCreateRoute
  "/barbershops/$barbershopUuid": typeof BarbershopsBarbershopUuidRoute
  "/analytics": typeof AnalyticsIndexRoute
  "/appointments": typeof AppointmentsIndexRoute
  "/barbershop-settings": typeof BarbershopSettingsIndexRoute
  "/barbershops": typeof BarbershopsIndexRoute
  "/become-barber": typeof BecomeBarberIndexRoute
  "/profile": typeof ProfileIndexRoute
  "/reviews": typeof ReviewsIndexRoute
  "/services": typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/appointments/create": typeof AppointmentsCreateRoute
  "/barbershops/$barbershopUuid": typeof BarbershopsBarbershopUuidRoute
  "/analytics": typeof AnalyticsIndexRoute
  "/appointments": typeof AppointmentsIndexRoute
  "/barbershop-settings": typeof BarbershopSettingsIndexRoute
  "/barbershops": typeof BarbershopsIndexRoute
  "/become-barber": typeof BecomeBarberIndexRoute
  "/profile": typeof ProfileIndexRoute
  "/reviews": typeof ReviewsIndexRoute
  "/services": typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/appointments/create": typeof AppointmentsCreateRoute
  "/barbershops/$barbershopUuid": typeof BarbershopsBarbershopUuidRoute
  "/analytics/": typeof AnalyticsIndexRoute
  "/appointments/": typeof AppointmentsIndexRoute
  "/barbershop-settings/": typeof BarbershopSettingsIndexRoute
  "/barbershops/": typeof BarbershopsIndexRoute
  "/become-barber/": typeof BecomeBarberIndexRoute
  "/profile/": typeof ProfileIndexRoute
  "/reviews/": typeof ReviewsIndexRoute
  "/services/": typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/appointments/create"
    | "/barbershops/$barbershopUuid"
    | "/analytics"
    | "/appointments"
    | "/barbershop-settings"
    | "/barbershops"
    | "/become-barber"
    | "/profile"
    | "/reviews"
    | "/services"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/appointments/create"
    | "/barbershops/$barbershopUuid"
    | "/analytics"
    | "/appointments"
    | "/barbershop-settings"
    | "/barbershops"
    | "/become-barber"
    | "/profile"
    | "/reviews"
    | "/services"
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/appointments/create"
    | "/barbershops/$barbershopUuid"
    | "/analytics/"
    | "/appointments/"
    | "/barbershop-settings/"
    | "/barbershops/"
    | "/become-barber/"
    | "/profile/"
    | "/reviews/"
    | "/services/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AppointmentsCreateRoute: typeof AppointmentsCreateRoute
  BarbershopsBarbershopUuidRoute: typeof BarbershopsBarbershopUuidRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  BarbershopSettingsIndexRoute: typeof BarbershopSettingsIndexRoute
  BarbershopsIndexRoute: typeof BarbershopsIndexRoute
  BecomeBarberIndexRoute: typeof BecomeBarberIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/services/": {
      id: "/services/"
      path: "/services"
      fullPath: "/services"
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reviews/": {
      id: "/reviews/"
      path: "/reviews"
      fullPath: "/reviews"
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile/": {
      id: "/profile/"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/become-barber/": {
      id: "/become-barber/"
      path: "/become-barber"
      fullPath: "/become-barber"
      preLoaderRoute: typeof BecomeBarberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/barbershops/": {
      id: "/barbershops/"
      path: "/barbershops"
      fullPath: "/barbershops"
      preLoaderRoute: typeof BarbershopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/barbershop-settings/": {
      id: "/barbershop-settings/"
      path: "/barbershop-settings"
      fullPath: "/barbershop-settings"
      preLoaderRoute: typeof BarbershopSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/appointments/": {
      id: "/appointments/"
      path: "/appointments"
      fullPath: "/appointments"
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/analytics/": {
      id: "/analytics/"
      path: "/analytics"
      fullPath: "/analytics"
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/barbershops/$barbershopUuid": {
      id: "/barbershops/$barbershopUuid"
      path: "/barbershops/$barbershopUuid"
      fullPath: "/barbershops/$barbershopUuid"
      preLoaderRoute: typeof BarbershopsBarbershopUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/appointments/create": {
      id: "/appointments/create"
      path: "/appointments/create"
      fullPath: "/appointments/create"
      preLoaderRoute: typeof AppointmentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AppointmentsCreateRoute: AppointmentsCreateRoute,
  BarbershopsBarbershopUuidRoute: BarbershopsBarbershopUuidRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  BarbershopSettingsIndexRoute: BarbershopSettingsIndexRoute,
  BarbershopsIndexRoute: BarbershopsIndexRoute,
  BecomeBarberIndexRoute: BecomeBarberIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
