/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TosRouteImport } from "./routes/tos"
import { Route as PrivacyPolicyRouteImport } from "./routes/privacy-policy"
import { Route as AuthRouteRouteImport } from "./routes/_auth/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProfileIndexRouteImport } from "./routes/profile/index"
import { Route as BarbershopsIndexRouteImport } from "./routes/barbershops/index"
import { Route as InvitationsCodeRouteImport } from "./routes/invitations/$code"
import { Route as BarbershopsBarbershopUuidRouteImport } from "./routes/barbershops/$barbershopUuid"
import { Route as AppointmentsCreateRouteImport } from "./routes/appointments/create"
import { Route as AuthRegisterRouteImport } from "./routes/_auth/register"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"
import { Route as AuthForgotPasswordRouteImport } from "./routes/_auth/forgot-password"
import { Route as ProfileBarbershopsSettingsRouteImport } from "./routes/profile/barbershops/settings"
import { Route as ProfileBarbershopsServicesIndexRouteImport } from "./routes/profile/barbershops/services/index"
import { Route as ProfileBarbershopsBarbersIndexRouteImport } from "./routes/profile/barbershops/barbers/index"
import { Route as ProfileBarbershopsAppointmentsIndexRouteImport } from "./routes/profile/barbershops/appointments/index"

const TosRoute = TosRouteImport.update({
  id: "/tos",
  path: "/tos",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: "/privacy-policy",
  path: "/privacy-policy",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => rootRouteImport,
} as any)
const BarbershopsIndexRoute = BarbershopsIndexRouteImport.update({
  id: "/barbershops/",
  path: "/barbershops/",
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsCodeRoute = InvitationsCodeRouteImport.update({
  id: "/invitations/$code",
  path: "/invitations/$code",
  getParentRoute: () => rootRouteImport,
} as any)
const BarbershopsBarbershopUuidRoute =
  BarbershopsBarbershopUuidRouteImport.update({
    id: "/barbershops/$barbershopUuid",
    path: "/barbershops/$barbershopUuid",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppointmentsCreateRoute = AppointmentsCreateRouteImport.update({
  id: "/appointments/create",
  path: "/appointments/create",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProfileBarbershopsSettingsRoute =
  ProfileBarbershopsSettingsRouteImport.update({
    id: "/profile/barbershops/settings",
    path: "/profile/barbershops/settings",
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileBarbershopsServicesIndexRoute =
  ProfileBarbershopsServicesIndexRouteImport.update({
    id: "/profile/barbershops/services/",
    path: "/profile/barbershops/services/",
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileBarbershopsBarbersIndexRoute =
  ProfileBarbershopsBarbersIndexRouteImport.update({
    id: "/profile/barbershops/barbers/",
    path: "/profile/barbershops/barbers/",
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileBarbershopsAppointmentsIndexRoute =
  ProfileBarbershopsAppointmentsIndexRouteImport.update({
    id: "/profile/barbershops/appointments/",
    path: "/profile/barbershops/appointments/",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/privacy-policy": typeof PrivacyPolicyRoute
  "/tos": typeof TosRoute
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/login": typeof AuthLoginRoute
  "/register": typeof AuthRegisterRoute
  "/appointments/create": typeof AppointmentsCreateRoute
  "/barbershops/$barbershopUuid": typeof BarbershopsBarbershopUuidRoute
  "/invitations/$code": typeof InvitationsCodeRoute
  "/barbershops": typeof BarbershopsIndexRoute
  "/profile": typeof ProfileIndexRoute
  "/profile/barbershops/settings": typeof ProfileBarbershopsSettingsRoute
  "/profile/barbershops/appointments": typeof ProfileBarbershopsAppointmentsIndexRoute
  "/profile/barbershops/barbers": typeof ProfileBarbershopsBarbersIndexRoute
  "/profile/barbershops/services": typeof ProfileBarbershopsServicesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/privacy-policy": typeof PrivacyPolicyRoute
  "/tos": typeof TosRoute
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/login": typeof AuthLoginRoute
  "/register": typeof AuthRegisterRoute
  "/appointments/create": typeof AppointmentsCreateRoute
  "/barbershops/$barbershopUuid": typeof BarbershopsBarbershopUuidRoute
  "/invitations/$code": typeof InvitationsCodeRoute
  "/barbershops": typeof BarbershopsIndexRoute
  "/profile": typeof ProfileIndexRoute
  "/profile/barbershops/settings": typeof ProfileBarbershopsSettingsRoute
  "/profile/barbershops/appointments": typeof ProfileBarbershopsAppointmentsIndexRoute
  "/profile/barbershops/barbers": typeof ProfileBarbershopsBarbersIndexRoute
  "/profile/barbershops/services": typeof ProfileBarbershopsServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteRouteWithChildren
  "/privacy-policy": typeof PrivacyPolicyRoute
  "/tos": typeof TosRoute
  "/_auth/forgot-password": typeof AuthForgotPasswordRoute
  "/_auth/login": typeof AuthLoginRoute
  "/_auth/register": typeof AuthRegisterRoute
  "/appointments/create": typeof AppointmentsCreateRoute
  "/barbershops/$barbershopUuid": typeof BarbershopsBarbershopUuidRoute
  "/invitations/$code": typeof InvitationsCodeRoute
  "/barbershops/": typeof BarbershopsIndexRoute
  "/profile/": typeof ProfileIndexRoute
  "/profile/barbershops/settings": typeof ProfileBarbershopsSettingsRoute
  "/profile/barbershops/appointments/": typeof ProfileBarbershopsAppointmentsIndexRoute
  "/profile/barbershops/barbers/": typeof ProfileBarbershopsBarbersIndexRoute
  "/profile/barbershops/services/": typeof ProfileBarbershopsServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/privacy-policy"
    | "/tos"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/appointments/create"
    | "/barbershops/$barbershopUuid"
    | "/invitations/$code"
    | "/barbershops"
    | "/profile"
    | "/profile/barbershops/settings"
    | "/profile/barbershops/appointments"
    | "/profile/barbershops/barbers"
    | "/profile/barbershops/services"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/privacy-policy"
    | "/tos"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/appointments/create"
    | "/barbershops/$barbershopUuid"
    | "/invitations/$code"
    | "/barbershops"
    | "/profile"
    | "/profile/barbershops/settings"
    | "/profile/barbershops/appointments"
    | "/profile/barbershops/barbers"
    | "/profile/barbershops/services"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/privacy-policy"
    | "/tos"
    | "/_auth/forgot-password"
    | "/_auth/login"
    | "/_auth/register"
    | "/appointments/create"
    | "/barbershops/$barbershopUuid"
    | "/invitations/$code"
    | "/barbershops/"
    | "/profile/"
    | "/profile/barbershops/settings"
    | "/profile/barbershops/appointments/"
    | "/profile/barbershops/barbers/"
    | "/profile/barbershops/services/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TosRoute: typeof TosRoute
  AppointmentsCreateRoute: typeof AppointmentsCreateRoute
  BarbershopsBarbershopUuidRoute: typeof BarbershopsBarbershopUuidRoute
  InvitationsCodeRoute: typeof InvitationsCodeRoute
  BarbershopsIndexRoute: typeof BarbershopsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileBarbershopsSettingsRoute: typeof ProfileBarbershopsSettingsRoute
  ProfileBarbershopsAppointmentsIndexRoute: typeof ProfileBarbershopsAppointmentsIndexRoute
  ProfileBarbershopsBarbersIndexRoute: typeof ProfileBarbershopsBarbersIndexRoute
  ProfileBarbershopsServicesIndexRoute: typeof ProfileBarbershopsServicesIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tos": {
      id: "/tos"
      path: "/tos"
      fullPath: "/tos"
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy-policy": {
      id: "/privacy-policy"
      path: "/privacy-policy"
      fullPath: "/privacy-policy"
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile/": {
      id: "/profile/"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/barbershops/": {
      id: "/barbershops/"
      path: "/barbershops"
      fullPath: "/barbershops"
      preLoaderRoute: typeof BarbershopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invitations/$code": {
      id: "/invitations/$code"
      path: "/invitations/$code"
      fullPath: "/invitations/$code"
      preLoaderRoute: typeof InvitationsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/barbershops/$barbershopUuid": {
      id: "/barbershops/$barbershopUuid"
      path: "/barbershops/$barbershopUuid"
      fullPath: "/barbershops/$barbershopUuid"
      preLoaderRoute: typeof BarbershopsBarbershopUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/appointments/create": {
      id: "/appointments/create"
      path: "/appointments/create"
      fullPath: "/appointments/create"
      preLoaderRoute: typeof AppointmentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/register": {
      id: "/_auth/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/_auth/forgot-password": {
      id: "/_auth/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/profile/barbershops/settings": {
      id: "/profile/barbershops/settings"
      path: "/profile/barbershops/settings"
      fullPath: "/profile/barbershops/settings"
      preLoaderRoute: typeof ProfileBarbershopsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile/barbershops/services/": {
      id: "/profile/barbershops/services/"
      path: "/profile/barbershops/services"
      fullPath: "/profile/barbershops/services"
      preLoaderRoute: typeof ProfileBarbershopsServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile/barbershops/barbers/": {
      id: "/profile/barbershops/barbers/"
      path: "/profile/barbershops/barbers"
      fullPath: "/profile/barbershops/barbers"
      preLoaderRoute: typeof ProfileBarbershopsBarbersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile/barbershops/appointments/": {
      id: "/profile/barbershops/appointments/"
      path: "/profile/barbershops/appointments"
      fullPath: "/profile/barbershops/appointments"
      preLoaderRoute: typeof ProfileBarbershopsAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TosRoute: TosRoute,
  AppointmentsCreateRoute: AppointmentsCreateRoute,
  BarbershopsBarbershopUuidRoute: BarbershopsBarbershopUuidRoute,
  InvitationsCodeRoute: InvitationsCodeRoute,
  BarbershopsIndexRoute: BarbershopsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileBarbershopsSettingsRoute: ProfileBarbershopsSettingsRoute,
  ProfileBarbershopsAppointmentsIndexRoute:
    ProfileBarbershopsAppointmentsIndexRoute,
  ProfileBarbershopsBarbersIndexRoute: ProfileBarbershopsBarbersIndexRoute,
  ProfileBarbershopsServicesIndexRoute: ProfileBarbershopsServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
