/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ChatRouteRouteImport } from './routes/chat/route'
import { Route as AuthedRoutesRouteRouteImport } from './routes/_authedRoutes/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as BarbershopsIndexRouteImport } from './routes/barbershops/index'
import { Route as ChatThreadIdRouteImport } from './routes/chat/$threadId'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as BarbershopsBarbershopUuidIndexRouteImport } from './routes/barbershops/$barbershopUuid/index'
import { Route as AuthedRoutesProfileIndexRouteImport } from './routes/_authedRoutes/profile/index'
import { Route as BarbershopsBarbershopUuidBookRouteImport } from './routes/barbershops/$barbershopUuid/book'
import { Route as AuthedRoutesProfileBarbershopsTeamIndexRouteImport } from './routes/_authedRoutes/profile/barbershops/team/index'
import { Route as AuthedRoutesProfileBarbershopsSettingsIndexRouteImport } from './routes/_authedRoutes/profile/barbershops/settings/index'
import { Route as AuthedRoutesProfileBarbershopsServicesIndexRouteImport } from './routes/_authedRoutes/profile/barbershops/services/index'
import { Route as AuthedRoutesProfileBarbershopsAppointmentsIndexRouteImport } from './routes/_authedRoutes/profile/barbershops/appointments/index'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoutesRouteRoute = AuthedRoutesRouteRouteImport.update({
  id: '/_authedRoutes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const BarbershopsIndexRoute = BarbershopsIndexRouteImport.update({
  id: '/barbershops/',
  path: '/barbershops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const BarbershopsBarbershopUuidIndexRoute =
  BarbershopsBarbershopUuidIndexRouteImport.update({
    id: '/barbershops/$barbershopUuid/',
    path: '/barbershops/$barbershopUuid/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedRoutesProfileIndexRoute =
  AuthedRoutesProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthedRoutesRouteRoute,
  } as any)
const BarbershopsBarbershopUuidBookRoute =
  BarbershopsBarbershopUuidBookRouteImport.update({
    id: '/barbershops/$barbershopUuid/book',
    path: '/barbershops/$barbershopUuid/book',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedRoutesProfileBarbershopsTeamIndexRoute =
  AuthedRoutesProfileBarbershopsTeamIndexRouteImport.update({
    id: '/profile/barbershops/team/',
    path: '/profile/barbershops/team/',
    getParentRoute: () => AuthedRoutesRouteRoute,
  } as any)
const AuthedRoutesProfileBarbershopsSettingsIndexRoute =
  AuthedRoutesProfileBarbershopsSettingsIndexRouteImport.update({
    id: '/profile/barbershops/settings/',
    path: '/profile/barbershops/settings/',
    getParentRoute: () => AuthedRoutesRouteRoute,
  } as any)
const AuthedRoutesProfileBarbershopsServicesIndexRoute =
  AuthedRoutesProfileBarbershopsServicesIndexRouteImport.update({
    id: '/profile/barbershops/services/',
    path: '/profile/barbershops/services/',
    getParentRoute: () => AuthedRoutesRouteRoute,
  } as any)
const AuthedRoutesProfileBarbershopsAppointmentsIndexRoute =
  AuthedRoutesProfileBarbershopsAppointmentsIndexRouteImport.update({
    id: '/profile/barbershops/appointments/',
    path: '/profile/barbershops/appointments/',
    getParentRoute: () => AuthedRoutesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/callback': typeof CallbackRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tos': typeof TosRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/barbershops/': typeof BarbershopsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/barbershops/$barbershopUuid/book': typeof BarbershopsBarbershopUuidBookRoute
  '/profile/': typeof AuthedRoutesProfileIndexRoute
  '/barbershops/$barbershopUuid/': typeof BarbershopsBarbershopUuidIndexRoute
  '/profile/barbershops/appointments/': typeof AuthedRoutesProfileBarbershopsAppointmentsIndexRoute
  '/profile/barbershops/services/': typeof AuthedRoutesProfileBarbershopsServicesIndexRoute
  '/profile/barbershops/settings/': typeof AuthedRoutesProfileBarbershopsSettingsIndexRoute
  '/profile/barbershops/team/': typeof AuthedRoutesProfileBarbershopsTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/callback': typeof CallbackRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tos': typeof TosRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/barbershops': typeof BarbershopsIndexRoute
  '/chat': typeof ChatIndexRoute
  '/barbershops/$barbershopUuid/book': typeof BarbershopsBarbershopUuidBookRoute
  '/profile': typeof AuthedRoutesProfileIndexRoute
  '/barbershops/$barbershopUuid': typeof BarbershopsBarbershopUuidIndexRoute
  '/profile/barbershops/appointments': typeof AuthedRoutesProfileBarbershopsAppointmentsIndexRoute
  '/profile/barbershops/services': typeof AuthedRoutesProfileBarbershopsServicesIndexRoute
  '/profile/barbershops/settings': typeof AuthedRoutesProfileBarbershopsSettingsIndexRoute
  '/profile/barbershops/team': typeof AuthedRoutesProfileBarbershopsTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authedRoutes': typeof AuthedRoutesRouteRouteWithChildren
  '/chat': typeof ChatRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/callback': typeof CallbackRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tos': typeof TosRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/barbershops/': typeof BarbershopsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/barbershops/$barbershopUuid/book': typeof BarbershopsBarbershopUuidBookRoute
  '/_authedRoutes/profile/': typeof AuthedRoutesProfileIndexRoute
  '/barbershops/$barbershopUuid/': typeof BarbershopsBarbershopUuidIndexRoute
  '/_authedRoutes/profile/barbershops/appointments/': typeof AuthedRoutesProfileBarbershopsAppointmentsIndexRoute
  '/_authedRoutes/profile/barbershops/services/': typeof AuthedRoutesProfileBarbershopsServicesIndexRoute
  '/_authedRoutes/profile/barbershops/settings/': typeof AuthedRoutesProfileBarbershopsSettingsIndexRoute
  '/_authedRoutes/profile/barbershops/team/': typeof AuthedRoutesProfileBarbershopsTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/ai'
    | '/callback'
    | '/llms.txt'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tos'
    | '/login'
    | '/register'
    | '/chat/$threadId'
    | '/barbershops/'
    | '/chat/'
    | '/barbershops/$barbershopUuid/book'
    | '/profile/'
    | '/barbershops/$barbershopUuid/'
    | '/profile/barbershops/appointments/'
    | '/profile/barbershops/services/'
    | '/profile/barbershops/settings/'
    | '/profile/barbershops/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/callback'
    | '/llms.txt'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tos'
    | '/login'
    | '/register'
    | '/chat/$threadId'
    | '/barbershops'
    | '/chat'
    | '/barbershops/$barbershopUuid/book'
    | '/profile'
    | '/barbershops/$barbershopUuid'
    | '/profile/barbershops/appointments'
    | '/profile/barbershops/services'
    | '/profile/barbershops/settings'
    | '/profile/barbershops/team'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authedRoutes'
    | '/chat'
    | '/ai'
    | '/callback'
    | '/llms.txt'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tos'
    | '/_auth/login'
    | '/_auth/register'
    | '/chat/$threadId'
    | '/barbershops/'
    | '/chat/'
    | '/barbershops/$barbershopUuid/book'
    | '/_authedRoutes/profile/'
    | '/barbershops/$barbershopUuid/'
    | '/_authedRoutes/profile/barbershops/appointments/'
    | '/_authedRoutes/profile/barbershops/services/'
    | '/_authedRoutes/profile/barbershops/settings/'
    | '/_authedRoutes/profile/barbershops/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRoutesRouteRoute: typeof AuthedRoutesRouteRouteWithChildren
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  AiRoute: typeof AiRoute
  CallbackRoute: typeof CallbackRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TosRoute: typeof TosRoute
  BarbershopsIndexRoute: typeof BarbershopsIndexRoute
  BarbershopsBarbershopUuidBookRoute: typeof BarbershopsBarbershopUuidBookRoute
  BarbershopsBarbershopUuidIndexRoute: typeof BarbershopsBarbershopUuidIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedRoutes': {
      id: '/_authedRoutes'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/barbershops/': {
      id: '/barbershops/'
      path: '/barbershops'
      fullPath: '/barbershops/'
      preLoaderRoute: typeof BarbershopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/barbershops/$barbershopUuid/': {
      id: '/barbershops/$barbershopUuid/'
      path: '/barbershops/$barbershopUuid'
      fullPath: '/barbershops/$barbershopUuid/'
      preLoaderRoute: typeof BarbershopsBarbershopUuidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedRoutes/profile/': {
      id: '/_authedRoutes/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedRoutesProfileIndexRouteImport
      parentRoute: typeof AuthedRoutesRouteRoute
    }
    '/barbershops/$barbershopUuid/book': {
      id: '/barbershops/$barbershopUuid/book'
      path: '/barbershops/$barbershopUuid/book'
      fullPath: '/barbershops/$barbershopUuid/book'
      preLoaderRoute: typeof BarbershopsBarbershopUuidBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedRoutes/profile/barbershops/team/': {
      id: '/_authedRoutes/profile/barbershops/team/'
      path: '/profile/barbershops/team'
      fullPath: '/profile/barbershops/team/'
      preLoaderRoute: typeof AuthedRoutesProfileBarbershopsTeamIndexRouteImport
      parentRoute: typeof AuthedRoutesRouteRoute
    }
    '/_authedRoutes/profile/barbershops/settings/': {
      id: '/_authedRoutes/profile/barbershops/settings/'
      path: '/profile/barbershops/settings'
      fullPath: '/profile/barbershops/settings/'
      preLoaderRoute: typeof AuthedRoutesProfileBarbershopsSettingsIndexRouteImport
      parentRoute: typeof AuthedRoutesRouteRoute
    }
    '/_authedRoutes/profile/barbershops/services/': {
      id: '/_authedRoutes/profile/barbershops/services/'
      path: '/profile/barbershops/services'
      fullPath: '/profile/barbershops/services/'
      preLoaderRoute: typeof AuthedRoutesProfileBarbershopsServicesIndexRouteImport
      parentRoute: typeof AuthedRoutesRouteRoute
    }
    '/_authedRoutes/profile/barbershops/appointments/': {
      id: '/_authedRoutes/profile/barbershops/appointments/'
      path: '/profile/barbershops/appointments'
      fullPath: '/profile/barbershops/appointments/'
      preLoaderRoute: typeof AuthedRoutesProfileBarbershopsAppointmentsIndexRouteImport
      parentRoute: typeof AuthedRoutesRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedRoutesRouteRouteChildren {
  AuthedRoutesProfileIndexRoute: typeof AuthedRoutesProfileIndexRoute
  AuthedRoutesProfileBarbershopsAppointmentsIndexRoute: typeof AuthedRoutesProfileBarbershopsAppointmentsIndexRoute
  AuthedRoutesProfileBarbershopsServicesIndexRoute: typeof AuthedRoutesProfileBarbershopsServicesIndexRoute
  AuthedRoutesProfileBarbershopsSettingsIndexRoute: typeof AuthedRoutesProfileBarbershopsSettingsIndexRoute
  AuthedRoutesProfileBarbershopsTeamIndexRoute: typeof AuthedRoutesProfileBarbershopsTeamIndexRoute
}

const AuthedRoutesRouteRouteChildren: AuthedRoutesRouteRouteChildren = {
  AuthedRoutesProfileIndexRoute: AuthedRoutesProfileIndexRoute,
  AuthedRoutesProfileBarbershopsAppointmentsIndexRoute:
    AuthedRoutesProfileBarbershopsAppointmentsIndexRoute,
  AuthedRoutesProfileBarbershopsServicesIndexRoute:
    AuthedRoutesProfileBarbershopsServicesIndexRoute,
  AuthedRoutesProfileBarbershopsSettingsIndexRoute:
    AuthedRoutesProfileBarbershopsSettingsIndexRoute,
  AuthedRoutesProfileBarbershopsTeamIndexRoute:
    AuthedRoutesProfileBarbershopsTeamIndexRoute,
}

const AuthedRoutesRouteRouteWithChildren =
  AuthedRoutesRouteRoute._addFileChildren(AuthedRoutesRouteRouteChildren)

interface ChatRouteRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRoutesRouteRoute: AuthedRoutesRouteRouteWithChildren,
  ChatRouteRoute: ChatRouteRouteWithChildren,
  AiRoute: AiRoute,
  CallbackRoute: CallbackRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TosRoute: TosRoute,
  BarbershopsIndexRoute: BarbershopsIndexRoute,
  BarbershopsBarbershopUuidBookRoute: BarbershopsBarbershopUuidBookRoute,
  BarbershopsBarbershopUuidIndexRoute: BarbershopsBarbershopUuidIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
