name: Deploy to Railway

on:
  push:
    branches: ["demo", "main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      actions: write
    uses: ./.github/workflows/version.yaml
  migrations:
    uses: ./.github/workflows/migrations.yaml
    secrets: inherit

        
  prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ${{ vars.SERVICE_ID }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/setup

      - name: Deploy to production
        run: railway up --service=${{ env.SVC_ID }}

  demo:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/demo' }}
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ${{ vars.PREVIEW_SERVICE_ID }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/setup

      - name: Deploy to production
        run: railway up --service=${{ env.SVC_ID }}
