name: Run migrations

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Set Database URL
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          else
            echo "DATABASE_URL=${{ secrets.DATABASE_PREVIEW_URL }}" >> $GITHUB_ENV
          fi

      - name: Generate migrations
        run: bun run db:generate

      - name: Run migrations
        run: bun run db:migrate
